version: '3.8'

networks:
  default:
    name: rhinpsservice
    external: false

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Web Console
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin12345678
    entrypoint: >
      /bin/sh -c "
      until mc alias set local http://minio:9000 admin admin12345678; do
        echo 'Waiting for MinIO...';
        sleep 2;
      done;
      mc mb --ignore-existing local/inps;
      mc anonymous set private local/inps;
      echo 'Bucket created successfully';
      "

    volumes:
      - minio_data:/data

    command: server /data --console-address ":9001"

  oracle-rhinpsservice-api-service:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-rhinpsservice-api-service
    environment:
      ORACLE_PASSWORD: ${ORACLE_PASSWORD}
    ports:
      - "${ORACLE_PORT}:1521"
    volumes:
      - oracle-data-21-rhinpsservice-api-service:/opt/oracle/oradata
    restart: unless-stopped

  rhinpsservice-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rhinpsservice-service
    env_file:
      - .env
    depends_on:
      - oracle-rhinpsservice-api-service
    environment:
      - SERVER_PORT=${SERVICE_PORT}
      - SERVICE_NAME=rhinpsservice-service
      - SPRING_ACTIVE_PROFILE=${SERVICE_PROFILE}
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@//${ORACLE_HOST}:${ORACLE_PORT}/${ORACLE_SERVICE_NAME}
      - SPRING_DATASOURCE_USERNAME=${ORACLE_USER}
      - SPRING_DATASOURCE_PASSWORD=${ORACLE_PASSWORD}
      - ENABLE_SWAGGER=${ENABLE_SWAGGER}
    ports:
      - "${SERVICE_PORT}:${SERVICE_PORT}"
    deploy:
      resources:
        limits:
          memory: 700m

volumes:
  oracle-data-21-rhinpsservice-api-service:
    driver: local
  minio_data:
    driver: local
