version: '3.8'

services:
  rhinpsservice-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: devtrustcv/rhinps-api:0.0.6
    container_name: rhinpsservice-service
    #platform: linux/arm64
    platform: linux/amd64
    env_file:
      - .env
    #environment:
      #- SERVER_PORT=${SERVICE_PORT}
      #- SERVICE_NAME=rhinpsservice-service
      #- SPRING_ACTIVE_PROFILE=${SPRING_ACTIVE_PROFILE}
      #- SPRING_DATASOURCE_URL=jdbc:oracle:thin:@//62.84.179.137:1521/xe
      #- ORACLE_USER=INPSDB
      #- ORACLE_PASSWORD=Pa$$w0rd
      #- ENABLE_SWAGGER=${ENABLE_SWAGGER}
      #- ORACLE_HOST=62.84.179.137
      #- ORACLE_PORT=1521
      #- ORACLE_SERVICE_NAME=xe
    ports:
      - "${SERVICE_PORT}:${SERVICE_PORT}"
    deploy:
      resources:
        limits:
          memory: 700m

#volumes:
 # oracle-data-21-rhinpsservice-api-service:
#    driver: local
