# Spring Cloud Kubernetes
spring.cloud.kubernetes.discovery.enabled=${KUBERNETES_DISCOVERY_ENABLED}
# ----------------------------------------------------------------------------
# JPA and Hibernate settings
# ----------------------------------------------------------------------------
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=${ENABLE_HIBERNATE_SQL:false}
spring.jpa.properties.hibernate.format_sql=${ENABLE_HIBERNATE_FORMAT_SQL:false}

# Authentication
spring.security.oauth2.resourceserver.jwt.issuer-uri=${IGRP_ACCESS_API_BASE_URL}

# Swagger
springdoc.swagger-ui.enabled=${ENABLE_SWAGGER:false}
springdoc.swagger-ui.operationsSorter=method
