# General
spring.config.import=optional:file:.env[.properties]

server.port=${SERVICE_PORT}

# Eureka Configurations
spring.cloud.refresh.enabled=false

# Spring Cloud Kubernetes
spring.cloud.kubernetes.discovery.enabled=${KUBERNETES_DISCOVERY_ENABLED:false}

# Logging Levels
#sets the baseline logging level for the entire application
logging.level.root=${LOGGING_LEVEL_ROOT:INFO}
#targets the web layer, allowing control over HTTP request/response logs
logging.level.org.springframework.web=${LOGGING_LEVEL_SPRING_WEB:INFO}
#applies to our application-specific logic, providing detailed logging where needed
logging.level.cv.inps.rh=${LOGGING_LEVEL_APP:INFO}
# Flyway debug: emit executed SQL statements
logging.level.org.flywaydb=TRACE
logging.level.org.flywaydb.core=TRACE
logging.level.org.flywaydb.core.internal=TRACE
logging.level.org.flywaydb.core.internal.sqlscript=TRACE
# Datasource
# Exemplo usando SID
# spring.datasource.url=jdbc:oracle:thin:@${ORACLE_HOST}:${ORACLE_PORT}:${ORACLE_SID}
spring.datasource.url=jdbc:oracle:thin:@//${ORACLE_HOST}:${ORACLE_PORT}/${ORACLE_SERVICE_NAME}
spring.datasource.username=${ORACLE_USER}
spring.datasource.password=${ORACLE_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA and Hibernate settings
spring.jpa.hibernate.ddl-auto=${HIBERNATE_DDL:update}
spring.jpa.show-sql=${ENABLE_HIBERNATE_SQL:false}
spring.jpa.properties.hibernate.format_sql=${ENABLE_HIBERNATE_FORMAT_SQL:false}
spring.jpa.properties.hibernate.dialect=org.hibernate.community.dialect.OracleLegacyDialect
#spring.jpa.properties.hibernate.default_schema=${DB_SCHEMA}

# Authentication
#spring.security.oauth2.resourceserver.jwt.issuer-uri=${AUTH_JWT_ISSUER}
auth.jwt.issuer=${AUTH_JWT_ISSUER}

