# Spring Cloud Kubernetes
spring.cloud.kubernetes.discovery.enabled=${KUBERNETES_DISCOVERY_ENABLED}

# Logging Levels
#sets the baseline logging level for the entire application
logging.level.root=${LOGGING_LEVEL_ROOT:INFO}
#targets the web layer, allowing control over HTTP request/response logs
logging.level.org.springframework.web=${LOGGING_LEVEL_SPRING_WEB:INFO}
#applies to our application-specific logic, providing detailed logging where needed
logging.level.cv.inps.rh=${LOGGING_LEVEL_APP:INFO}

# Datasource configuration
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA and Hibernate settings
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=${ENABLE_HIBERNATE_SQL:false}
spring.jpa.properties.hibernate.format_sql=${ENABLE_HIBERNATE_FORMAT_SQL:false}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.Oracle12cDialect

# Authentication
spring.security.oauth2.resourceserver.jwt.issuer-uri=${AUTH_JWT_ISSUER}

# Swagger
springdoc.swagger-ui.enabled=${ENABLE_SWAGGER:false}
springdoc.swagger-ui.operationsSorter=method

