# General
spring.config.import=optional:file:.env[.properties]
spring.jpa.open-in-view=false

spring.application.name=RHINPSSERVICE
# Default profile
spring.profiles.active=${SPRING_ACTIVE_PROFILE:development}

server.shutdown=graceful
management.endpoint.health.probes.enabled=true

spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=false
spring.flyway.baseline-version=0
spring.flyway.validate-on-migrate=false
spring.flyway.locations=classpath:db/migration

# Habilita batch inserts
spring.jpa.properties.hibernate.jdbc.batch_size=50

# Permite reusar prepared statements
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect


