package cv.inps.rh.shared.application.constants.custom;

import io.prometheus.client.SimpleCollector;

public enum Referencia {
  RENDIMENTO,
  DESCONTO,
  REGISTO_COLABORADOR,
  CONTRATO,
  RENOVACAO_CONTRATO,
  FAMILIA,
  ESTADO_COLABORADOR,
  DADOS_ACADEMICOS,
  DADOS_BANCARIOS,
  DADOS_PESSOAIS,
  MOBILIDADE,
  REGIME,
  SITUACAO_LABORAL,
  SUBSTITUICAO,
  CARREIRA,
  FALTA,
  DISPENSA,
  HORA_EXTRA,
  FERIA,
  JUSTIFICAR_FALTA,
  ORDEM_SERVICO

}
