package cv.inps.rh.shared.application.constants.custom;

public enum TableName {
  RH_T_DISPENSA,
  RH_T_FERIAS_GOZADAS,
  RH_T_FALTA,
  RH_T_FUNCIONARIOS,
  RH_T_HORA_EXTRA,
  RH_T_MISSAO_SERVICO,
  RH_T_MISSAO_LOGISTICA,
  RH_T_MISSAO_REQUISICAO,
  RH_T_ORDEM_SERVICO,
  RH_T_PEDIDO,
  RH_T_PROCESSO_DISCIPLINAR,
  RH_T_CONTRATO_VINCULO,
  RH_T_EMPRESTIMO,
  RH_T_EVOLUCAO_CARREIRA,
  ADIANTAMENTO_EMPRESTIMO,
  RH_T_DECLARACAO,
  RH_T_ABONOS_BENEFICIOS
}
