package cv.inps.rh.emprestimo.domain.service.constants;

public enum EtapaEmprestimo {
  PEDIDO,
  ANALISE_RH_PEDIDO,
  ANALISE_RH_ADIANTAMENTO,
  ANALISE_RH_REFORCO,
  ANEXAR_CONTRATO_ADIANTAMENTO,
  VERIFICACAO_ADIANTAMENTO,
  ANALISE_FINANCEIRA_PEDIDO,
  ANALISE_FINANCEIRA_REFORCO,
  AUTORIZAR_COMISSAO_EXECUTIVA_PEDIDO,
  AUTORIZAR_COMISSAO_EXECUTIVA_REFORCO,
  ELABORAR_CONTRATO_PEDIDO,
  ELABORAR_CONTRATO_REFORCO,
  PAGAMENTO,
}
