package cv.inps.rh.emprestimo.domain.service.constants;

public enum EtapaEmprestimo {
  PEDIDO,
  ANALISE_RH_PEDIDO,
  ANALISE_RH_ADIANTAMENTO,
  VERIFICACAO_ADIANTAMENTO,
  ANALISE_FINANCEIRA,
  AUTORIZAR_COMISSAO_EXECUTIVA,
  ELABORAR_CONTRATO
}
