package cv.inps.rh.emprestimo.domain.service.constants;

public enum TipoSituacao {

  ADIANTAMENTO_PAGAMENTO_ANTECIPADO,

  ADIANTAMENTO_DIMINUICAO_PRESTACAO,

  ADIANTAMENTO_PAGAMENTO_ANTECIPADO_DIMINUICAO_PRESTACAO,

  REFORCO_AUMENTO_VALOR,

  REFORCO_AUMENTO_PRESTACAO,

  REFORCO_AUMENTO_VALOR_AUMENTO_PRESTACAO
}
