package cv.inps.rh.shared.domain.service.model;

public enum OrdemServico {

  FIM_COMISSAO_SERVICO,
  CONVERSAO_CONTRATO,
  LICENSA_SEM_VENCIMENTO,

  PROGRESSAO_CARGO,
  PROGRESSAO_CATEGORIA,
  SUBSTITUICAO,
  TRANSFERENCIA,
  MOBILIDADE_INTERNA,
  REQUALIFICACAO,
  NOMEACAO_COORDENADOR

}
