-- Idempotent seed for GLB_T_GEOGRAFIA
MERGE INTO GLB_T_GEOGRAFIA g
USING (
  SELECT 1 ID,
         'CABO VERDE' NOME,
         'CABOVERDIANA' NACIONALIDADE,
         NULL GEOGR_ID,
         NULL PAIS,
         1 NIVEL_DETALHE,
         'República de Cabo Verde' NOME_OFICIAL,
         'N' FLAG_ALTER,
         'CABO VERDE' NOME_NORM,
         'PAIS' TP_GEOG_CD,
         'A' FLG_SITUACAO
  FROM dual
) src
ON (g."ID" = src.ID)
WHEN MATCHED THEN UPDATE SET
  g."NOME" = src.NOME,
  g."NACIONALIDADE" = src.NACIONALIDADE,
  g."GEOGR_ID" = src.GEOGR_ID,
  g."PAIS" = src.PAIS,
  g."NIVEL_DETALHE" = src.NIVEL_DETALHE,
  g."NOME_OFICIAL" = src.NOME_OFICIAL,
  g."FLAG_ALTER" = src.FLAG_ALTER,
  g."NOME_NORM" = src.NOME_NORM,
  g."TP_GEOG_CD" = src.TP_GEOG_CD,
  g."FLG_SITUACAO" = src.FLG_SITUACAO
WHEN NOT MATCHED THEN INSERT ("ID","NOME","NACIONALIDADE","GEOGR_ID","PAIS","NIVEL_DETALHE","NOME_OFICIAL","FLAG_ALTER","NOME_NORM","TP_GEOG_CD","FLG_SITUACAO")
VALUES (src.ID,src.NOME,src.NACIONALIDADE,src.GEOGR_ID,src.PAIS,src.NIVEL_DETALHE,src.NOME_OFICIAL,src.FLAG_ALTER,src.NOME_NORM,src.TP_GEOG_CD,src.FLG_SITUACAO);

MERGE INTO GLB_T_GEOGRAFIA g
USING (
  SELECT 2 ID, 'PORTUGAL' NOME, 'PORTUGUESA' NACIONALIDADE, NULL GEOGR_ID, NULL PAIS,
         1 NIVEL_DETALHE, 'República Portuguesa' NOME_OFICIAL, 'N' FLAG_ALTER,
         'PORTUGAL' NOME_NORM, 'PAIS' TP_GEOG_CD, 'A' FLG_SITUACAO
  FROM dual
) src
ON (g."ID" = src.ID)
WHEN MATCHED THEN UPDATE SET
  g."NOME" = src.NOME,
  g."NACIONALIDADE" = src.NACIONALIDADE,
  g."GEOGR_ID" = src.GEOGR_ID,
  g."PAIS" = src.PAIS,
  g."NIVEL_DETALHE" = src.NIVEL_DETALHE,
  g."NOME_OFICIAL" = src.NOME_OFICIAL,
  g."FLAG_ALTER" = src.FLAG_ALTER,
  g."NOME_NORM" = src.NOME_NORM,
  g."TP_GEOG_CD" = src.TP_GEOG_CD,
  g."FLG_SITUACAO" = src.FLG_SITUACAO
WHEN NOT MATCHED THEN INSERT ("ID","NOME","NACIONALIDADE","GEOGR_ID","PAIS","NIVEL_DETALHE","NOME_OFICIAL","FLAG_ALTER","NOME_NORM","TP_GEOG_CD","FLG_SITUACAO")
VALUES (src.ID,src.NOME,src.NACIONALIDADE,src.GEOGR_ID,src.PAIS,src.NIVEL_DETALHE,src.NOME_OFICIAL,src.FLAG_ALTER,src.NOME_NORM,src.TP_GEOG_CD,src.FLG_SITUACAO);

MERGE INTO GLB_T_GEOGRAFIA g
USING (
  SELECT 3 ID, 'BRASIL' NOME, 'BRASILEIRA' NACIONALIDADE, NULL GEOGR_ID, NULL PAIS,
         1 NIVEL_DETALHE, 'República Federativa do Brasil' NOME_OFICIAL, 'N' FLAG_ALTER,
         'BRASIL' NOME_NORM, 'PAIS' TP_GEOG_CD, 'A' FLG_SITUACAO
  FROM dual
) src
ON (g."ID" = src.ID)
WHEN MATCHED THEN UPDATE SET
  g."NOME" = src.NOME,
  g."NACIONALIDADE" = src.NACIONALIDADE,
  g."GEOGR_ID" = src.GEOGR_ID,
  g."PAIS" = src.PAIS,
  g."NIVEL_DETALHE" = src.NIVEL_DETALHE,
  g."NOME_OFICIAL" = src.NOME_OFICIAL,
  g."FLAG_ALTER" = src.FLAG_ALTER,
  g."NOME_NORM" = src.NOME_NORM,
  g."TP_GEOG_CD" = src.TP_GEOG_CD,
  g."FLG_SITUACAO" = src.FLG_SITUACAO
WHEN NOT MATCHED THEN INSERT ("ID","NOME","NACIONALIDADE","GEOGR_ID","PAIS","NIVEL_DETALHE","NOME_OFICIAL","FLAG_ALTER","NOME_NORM","TP_GEOG_CD","FLG_SITUACAO")
VALUES (src.ID,src.NOME,src.NACIONALIDADE,src.GEOGR_ID,src.PAIS,src.NIVEL_DETALHE,src.NOME_OFICIAL,src.FLAG_ALTER,src.NOME_NORM,src.TP_GEOG_CD,src.FLG_SITUACAO);

MERGE INTO GLB_T_GEOGRAFIA g
USING (
  SELECT 4 ID, 'ANGOLA' NOME, 'ANGOLANA' NACIONALIDADE, NULL GEOGR_ID, NULL PAIS,
         1 NIVEL_DETALHE, 'República de Angola' NOME_OFICIAL, 'N' FLAG_ALTER,
         'ANGOLA' NOME_NORM, 'PAIS' TP_GEOG_CD, 'A' FLG_SITUACAO
  FROM dual
) src
ON (g."ID" = src.ID)
WHEN MATCHED THEN UPDATE SET
  g."NOME" = src.NOME,
  g."NACIONALIDADE" = src.NACIONALIDADE,
  g."GEOGR_ID" = src.GEOGR_ID,
  g."PAIS" = src.PAIS,
  g."NIVEL_DETALHE" = src.NIVEL_DETALHE,
  g."NOME_OFICIAL" = src.NOME_OFICIAL,
  g."FLAG_ALTER" = src.FLAG_ALTER,
  g."NOME_NORM" = src.NOME_NORM,
  g."TP_GEOG_CD" = src.TP_GEOG_CD,
  g."FLG_SITUACAO" = src.FLG_SITUACAO
WHEN NOT MATCHED THEN INSERT ("ID","NOME","NACIONALIDADE","GEOGR_ID","PAIS","NIVEL_DETALHE","NOME_OFICIAL","FLAG_ALTER","NOME_NORM","TP_GEOG_CD","FLG_SITUACAO")
VALUES (src.ID,src.NOME,src.NACIONALIDADE,src.GEOGR_ID,src.PAIS,src.NIVEL_DETALHE,src.NOME_OFICIAL,src.FLAG_ALTER,src.NOME_NORM,src.TP_GEOG_CD,src.FLG_SITUACAO);

MERGE INTO GLB_T_GEOGRAFIA g
USING (
  SELECT 5 ID, 'MOÇAMBIQUE' NOME, 'MOÇAMBICANA' NACIONALIDADE, NULL GEOGR_ID, NULL PAIS,
         1 NIVEL_DETALHE, 'República de Moçambique' NOME_OFICIAL, 'N' FLAG_ALTER,
         'MOÇAMBIQUE' NOME_NORM, 'PAIS' TP_GEOG_CD, 'A' FLG_SITUACAO
  FROM dual
) src
ON (g."ID" = src.ID)
WHEN MATCHED THEN UPDATE SET
  g."NOME" = src.NOME,
  g."NACIONALIDADE" = src.NACIONALIDADE,
  g."GEOGR_ID" = src.GEOGR_ID,
  g."PAIS" = src.PAIS,
  g."NIVEL_DETALHE" = src.NIVEL_DETALHE,
  g."NOME_OFICIAL" = src.NOME_OFICIAL,
  g."FLAG_ALTER" = src.FLAG_ALTER,
  g."NOME_NORM" = src.NOME_NORM,
  g."TP_GEOG_CD" = src.TP_GEOG_CD,
  g."FLG_SITUACAO" = src.FLG_SITUACAO
WHEN NOT MATCHED THEN INSERT ("ID","NOME","NACIONALIDADE","GEOGR_ID","PAIS","NIVEL_DETALHE","NOME_OFICIAL","FLAG_ALTER","NOME_NORM","TP_GEOG_CD","FLG_SITUACAO")
VALUES (src.ID,src.NOME,src.NACIONALIDADE,src.GEOGR_ID,src.PAIS,src.NIVEL_DETALHE,src.NOME_OFICIAL,src.FLAG_ALTER,src.NOME_NORM,src.TP_GEOG_CD,src.FLG_SITUACAO);

MERGE INTO GLB_T_GEOGRAFIA g
USING (
  SELECT 6 ID, 'GUINÉ-BISSAU' NOME, 'GUINEENSE' NACIONALIDADE, NULL GEOGR_ID, NULL PAIS,
         1 NIVEL_DETALHE, 'República da Guiné-Bissau' NOME_OFICIAL, 'N' FLAG_ALTER,
         'GUINÉ-BISSAU' NOME_NORM, 'PAIS' TP_GEOG_CD, 'A' FLG_SITUACAO
  FROM dual
) src
ON (g."ID" = src.ID)
WHEN MATCHED THEN UPDATE SET
  g."NOME" = src.NOME,
  g."NACIONALIDADE" = src.NACIONALIDADE,
  g."GEOGR_ID" = src.GEOGR_ID,
  g."PAIS" = src.PAIS,
  g."NIVEL_DETALHE" = src.NIVEL_DETALHE,
  g."NOME_OFICIAL" = src.NOME_OFICIAL,
  g."FLAG_ALTER" = src.FLAG_ALTER,
  g."NOME_NORM" = src.NOME_NORM,
  g."TP_GEOG_CD" = src.TP_GEOG_CD,
  g."FLG_SITUACAO" = src.FLG_SITUACAO
WHEN NOT MATCHED THEN INSERT ("ID","NOME","NACIONALIDADE","GEOGR_ID","PAIS","NIVEL_DETALHE","NOME_OFICIAL","FLAG_ALTER","NOME_NORM","TP_GEOG_CD","FLG_SITUACAO")
VALUES (src.ID,src.NOME,src.NACIONALIDADE,src.GEOGR_ID,src.PAIS,src.NIVEL_DETALHE,src.NOME_OFICIAL,src.FLAG_ALTER,src.NOME_NORM,src.TP_GEOG_CD,src.FLG_SITUACAO);

MERGE INTO GLB_T_GEOGRAFIA g
USING (
  SELECT 7 ID, 'SÃO TOMÉ E PRÍNCIPE' NOME, 'SANTOMENSE' NACIONALIDADE, NULL GEOGR_ID, NULL PAIS,
         1 NIVEL_DETALHE, 'República Democrática de São Tomé e Príncipe' NOME_OFICIAL, 'N' FLAG_ALTER,
         'SÃO TOMÉ E PRÍNCIPE' NOME_NORM, 'PAIS' TP_GEOG_CD, 'A' FLG_SITUACAO
  FROM dual
) src
ON (g."ID" = src.ID)
WHEN MATCHED THEN UPDATE SET
  g."NOME" = src.NOME,
  g."NACIONALIDADE" = src.NACIONALIDADE,
  g."GEOGR_ID" = src.GEOGR_ID,
  g."PAIS" = src.PAIS,
  g."NIVEL_DETALHE" = src.NIVEL_DETALHE,
  g."NOME_OFICIAL" = src.NOME_OFICIAL,
  g."FLAG_ALTER" = src.FLAG_ALTER,
  g."NOME_NORM" = src.NOME_NORM,
  g."TP_GEOG_CD" = src.TP_GEOG_CD,
  g."FLG_SITUACAO" = src.FLG_SITUACAO
WHEN NOT MATCHED THEN INSERT ("ID","NOME","NACIONALIDADE","GEOGR_ID","PAIS","NIVEL_DETALHE","NOME_OFICIAL","FLAG_ALTER","NOME_NORM","TP_GEOG_CD","FLG_SITUACAO")
VALUES (src.ID,src.NOME,src.NACIONALIDADE,src.GEOGR_ID,src.PAIS,src.NIVEL_DETALHE,src.NOME_OFICIAL,src.FLAG_ALTER,src.NOME_NORM,src.TP_GEOG_CD,src.FLG_SITUACAO);

MERGE INTO GLB_T_GEOGRAFIA g
USING (
  SELECT 8 ID, 'TIMOR-LESTE' NOME, 'TIMORENSE' NACIONALIDADE, NULL GEOGR_ID, NULL PAIS,
         1 NIVEL_DETALHE, 'República Democrática de Timor-Leste' NOME_OFICIAL, 'N' FLAG_ALTER,
         'TIMOR-LESTE' NOME_NORM, 'PAIS' TP_GEOG_CD, 'A' FLG_SITUACAO
  FROM dual
) src
ON (g."ID" = src.ID)
WHEN MATCHED THEN UPDATE SET
  g."NOME" = src.NOME,
  g."NACIONALIDADE" = src.NACIONALIDADE,
  g."GEOGR_ID" = src.GEOGR_ID,
  g."PAIS" = src.PAIS,
  g."NIVEL_DETALHE" = src.NIVEL_DETALHE,
  g."NOME_OFICIAL" = src.NOME_OFICIAL,
  g."FLAG_ALTER" = src.FLAG_ALTER,
  g."NOME_NORM" = src.NOME_NORM,
  g."TP_GEOG_CD" = src.TP_GEOG_CD,
  g."FLG_SITUACAO" = src.FLG_SITUACAO
WHEN NOT MATCHED THEN INSERT ("ID","NOME","NACIONALIDADE","GEOGR_ID","PAIS","NIVEL_DETALHE","NOME_OFICIAL","FLAG_ALTER","NOME_NORM","TP_GEOG_CD","FLG_SITUACAO")
VALUES (src.ID,src.NOME,src.NACIONALIDADE,src.GEOGR_ID,src.PAIS,src.NIVEL_DETALHE,src.NOME_OFICIAL,src.FLAG_ALTER,src.NOME_NORM,src.TP_GEOG_CD,src.FLG_SITUACAO);

MERGE INTO GLB_T_GEOGRAFIA g
USING (
  SELECT 9 ID, 'ESPANHA' NOME, 'ESPANHOLA' NACIONALIDADE, NULL GEOGR_ID, NULL PAIS,
         1 NIVEL_DETALHE, 'Reino de Espanha' NOME_OFICIAL, 'N' FLAG_ALTER,
         'ESPANHA' NOME_NORM, 'PAIS' TP_GEOG_CD, 'A' FLG_SITUACAO
  FROM dual
) src
ON (g."ID" = src.ID)
WHEN MATCHED THEN UPDATE SET
  g."NOME" = src.NOME,
  g."NACIONALIDADE" = src.NACIONALIDADE,
  g."GEOGR_ID" = src.GEOGR_ID,
  g."PAIS" = src.PAIS,
  g."NIVEL_DETALHE" = src.NIVEL_DETALHE,
  g."NOME_OFICIAL" = src.NOME_OFICIAL,
  g."FLAG_ALTER" = src.FLAG_ALTER,
  g."NOME_NORM" = src.NOME_NORM,
  g."TP_GEOG_CD" = src.TP_GEOG_CD,
  g."FLG_SITUACAO" = src.FLG_SITUACAO
WHEN NOT MATCHED THEN INSERT ("ID","NOME","NACIONALIDADE","GEOGR_ID","PAIS","NIVEL_DETALHE","NOME_OFICIAL","FLAG_ALTER","NOME_NORM","TP_GEOG_CD","FLG_SITUACAO")
VALUES (src.ID,src.NOME,src.NACIONALIDADE,src.GEOGR_ID,src.PAIS,src.NIVEL_DETALHE,src.NOME_OFICIAL,src.FLAG_ALTER,src.NOME_NORM,src.TP_GEOG_CD,src.FLG_SITUACAO);

MERGE INTO GLB_T_GEOGRAFIA g
USING (
  SELECT 10 ID, 'FRANÇA' NOME, 'FRANCESA' NACIONALIDADE, NULL GEOGR_ID, NULL PAIS,
         1 NIVEL_DETALHE, 'República Francesa' NOME_OFICIAL, 'N' FLAG_ALTER,
         'FRANÇA' NOME_NORM, 'PAIS' TP_GEOG_CD, 'A' FLG_SITUACAO
  FROM dual
) src
ON (g."ID" = src.ID)
WHEN MATCHED THEN UPDATE SET
  g."NOME" = src.NOME,
  g."NACIONALIDADE" = src.NACIONALIDADE,
  g."GEOGR_ID" = src.GEOGR_ID,
  g."PAIS" = src.PAIS,
  g."NIVEL_DETALHE" = src.NIVEL_DETALHE,
  g."NOME_OFICIAL" = src.NOME_OFICIAL,
  g."FLAG_ALTER" = src.FLAG_ALTER,
  g."NOME_NORM" = src.NOME_NORM,
  g."TP_GEOG_CD" = src.TP_GEOG_CD,
  g."FLG_SITUACAO" = src.FLG_SITUACAO
WHEN NOT MATCHED THEN INSERT ("ID","NOME","NACIONALIDADE","GEOGR_ID","PAIS","NIVEL_DETALHE","NOME_OFICIAL","FLAG_ALTER","NOME_NORM","TP_GEOG_CD","FLG_SITUACAO")
VALUES (src.ID,src.NOME,src.NACIONALIDADE,src.GEOGR_ID,src.PAIS,src.NIVEL_DETALHE,src.NOME_OFICIAL,src.FLAG_ALTER,src.NOME_NORM,src.TP_GEOG_CD,src.FLG_SITUACAO);

MERGE INTO GLB_T_GEOGRAFIA g
USING (
  SELECT 11 ID, 'ESTADOS UNIDOS' NOME, 'ESTADUNIDENSE' NACIONALIDADE, NULL GEOGR_ID, NULL PAIS,
         1 NIVEL_DETALHE, 'Estados Unidos da América' NOME_OFICIAL, 'N' FLAG_ALTER,
         'ESTADOS UNIDOS' NOME_NORM, 'PAIS' TP_GEOG_CD, 'A' FLG_SITUACAO
  FROM dual
) src
ON (g."ID" = src.ID)
WHEN MATCHED THEN UPDATE SET
  g."NOME" = src.NOME,
  g."NACIONALIDADE" = src.NACIONALIDADE,
  g."GEOGR_ID" = src.GEOGR_ID,
  g."PAIS" = src.PAIS,
  g."NIVEL_DETALHE" = src.NIVEL_DETALHE,
  g."NOME_OFICIAL" = src.NOME_OFICIAL,
  g."FLAG_ALTER" = src.FLAG_ALTER,
  g."NOME_NORM" = src.NOME_NORM,
  g."TP_GEOG_CD" = src.TP_GEOG_CD,
  g."FLG_SITUACAO" = src.FLG_SITUACAO
WHEN NOT MATCHED THEN INSERT ("ID","NOME","NACIONALIDADE","GEOGR_ID","PAIS","NIVEL_DETALHE","NOME_OFICIAL","FLAG_ALTER","NOME_NORM","TP_GEOG_CD","FLG_SITUACAO")
VALUES (src.ID,src.NOME,src.NACIONALIDADE,src.GEOGR_ID,src.PAIS,src.NIVEL_DETALHE,src.NOME_OFICIAL,src.FLAG_ALTER,src.NOME_NORM,src.TP_GEOG_CD,src.FLG_SITUACAO);

MERGE INTO GLB_T_GEOGRAFIA g
USING (
  SELECT 12 ID, 'NIGÉRIA' NOME, 'NIGERIANA' NACIONALIDADE, NULL GEOGR_ID, NULL PAIS,
         1 NIVEL_DETALHE, 'República Federal da Nigéria' NOME_OFICIAL, 'N' FLAG_ALTER,
         'NIGÉRIA' NOME_NORM, 'PAIS' TP_GEOG_CD, 'A' FLG_SITUACAO
  FROM dual
) src
ON (g."ID" = src.ID)
WHEN MATCHED THEN UPDATE SET
  g."NOME" = src.NOME,
  g."NACIONALIDADE" = src.NACIONALIDADE,
  g."GEOGR_ID" = src.GEOGR_ID,
  g."PAIS" = src.PAIS,
  g."NIVEL_DETALHE" = src.NIVEL_DETALHE,
  g."NOME_OFICIAL" = src.NOME_OFICIAL,
  g."FLAG_ALTER" = src.FLAG_ALTER,
  g."NOME_NORM" = src.NOME_NORM,
  g."TP_GEOG_CD" = src.TP_GEOG_CD,
  g."FLG_SITUACAO" = src.FLG_SITUACAO
WHEN NOT MATCHED THEN INSERT ("ID","NOME","NACIONALIDADE","GEOGR_ID","PAIS","NIVEL_DETALHE","NOME_OFICIAL","FLAG_ALTER","NOME_NORM","TP_GEOG_CD","FLG_SITUACAO")
VALUES (src.ID,src.NOME,src.NACIONALIDADE,src.GEOGR_ID,src.PAIS,src.NIVEL_DETALHE,src.NOME_OFICIAL,src.FLAG_ALTER,src.NOME_NORM,src.TP_GEOG_CD,src.FLG_SITUACAO);