-- Idempotent seed: dominio PARECER, referencia ANALISE_RH.
-- Empréstimo v2 — Análise RH passa a ter parecer em dois níveis (técnico + responsável),
-- ambos usando os mesmos códigos FAVORAVEL/DESFAVORAVEL/RETIFICACAO (ParecerProcesso),
-- mas com rótulos próprios ("Conforme"/"Não Conforme"/"Retificação") distintos dos
-- rótulos de Análise Financeira/Autorização CE, que continuam a usar o dominio PARECER
-- sem referencia (Favorável/Desfavorável/Retificação).
MERGE INTO RH_T_DOMAINS d
USING (
  SELECT 'PARECER' DOMINIO, 'ANALISE_RH' REFERENCIA, 'FAVORAVEL' VALOR, 'Conforme' DESCRICAO FROM dual
) src
ON (d.DOMINIO = src.DOMINIO AND d.REFERENCIA = src.REFERENCIA AND d.VALOR = src.VALOR)
WHEN MATCHED THEN UPDATE SET
  d.DESCRICAO = src.DESCRICAO,
  d.ESTADO = 'A'
WHEN NOT MATCHED THEN INSERT (ID, DOMINIO, VALOR, DESCRICAO, REFERENCIA, ESTADO, DATA_REGISTO, USER_REGISTO_ID, USER_REGISTO_NAME)
VALUES (SEQ_DOMAINS.NEXTVAL, src.DOMINIO, src.VALOR, src.DESCRICAO, src.REFERENCIA, 'A', SYSDATE, 0, 'FLYWAY_MIGRATION');

MERGE INTO RH_T_DOMAINS d
USING (
  SELECT 'PARECER' DOMINIO, 'ANALISE_RH' REFERENCIA, 'DESFAVORAVEL' VALOR, 'Não Conforme' DESCRICAO FROM dual
) src
ON (d.DOMINIO = src.DOMINIO AND d.REFERENCIA = src.REFERENCIA AND d.VALOR = src.VALOR)
WHEN MATCHED THEN UPDATE SET
  d.DESCRICAO = src.DESCRICAO,
  d.ESTADO = 'A'
WHEN NOT MATCHED THEN INSERT (ID, DOMINIO, VALOR, DESCRICAO, REFERENCIA, ESTADO, DATA_REGISTO, USER_REGISTO_ID, USER_REGISTO_NAME)
VALUES (SEQ_DOMAINS.NEXTVAL, src.DOMINIO, src.VALOR, src.DESCRICAO, src.REFERENCIA, 'A', SYSDATE, 0, 'FLYWAY_MIGRATION');

MERGE INTO RH_T_DOMAINS d
USING (
  SELECT 'PARECER' DOMINIO, 'ANALISE_RH' REFERENCIA, 'RETIFICACAO' VALOR, 'Retificação' DESCRICAO FROM dual
) src
ON (d.DOMINIO = src.DOMINIO AND d.REFERENCIA = src.REFERENCIA AND d.VALOR = src.VALOR)
WHEN MATCHED THEN UPDATE SET
  d.DESCRICAO = src.DESCRICAO,
  d.ESTADO = 'A'
WHEN NOT MATCHED THEN INSERT (ID, DOMINIO, VALOR, DESCRICAO, REFERENCIA, ESTADO, DATA_REGISTO, USER_REGISTO_ID, USER_REGISTO_NAME)
VALUES (SEQ_DOMAINS.NEXTVAL, src.DOMINIO, src.VALOR, src.DESCRICAO, src.REFERENCIA, 'A', SYSDATE, 0, 'FLYWAY_MIGRATION');
