-- Migração: Normalizar valores da coluna ETAPA em RH_T_MISSAO_SERVICO
-- Data: 2026-05-30
-- Motivo: Alinhamento com a spec funcional (valores curtos conforme definidos na spec)
--
-- Mapeamento:
--   ETAPA_1_SUBMISSAO_AUTORIZACAO  -> SUBMISSAO
--   ETAPA_2_ANALISE_RH             -> ANALISE
--   ETAPA_3_EMISSAO_REQUISICAO     -> EMISSAO_REQUISICAO
--   ETAPA_4_PROCESSAMENTO_LOGISTICO-> LOGISTICA
--   ETAPA_5_CABIMENTACAO_SGAL      -> CABIMENTO
--   ETAPA_6_AUTORIZACAO_RH         -> CABIMENTO  (sem valor dedicado na spec)
--   ETAPA_7_PAGAMENTO_FINANCEIRO   -> PAGAMENTO

UPDATE RH_T_MISSAO_SERVICO SET ETAPA = 'SUBMISSAO'         WHERE ETAPA = 'ETAPA_1_SUBMISSAO_AUTORIZACAO';
UPDATE RH_T_MISSAO_SERVICO SET ETAPA = 'SUBMISSAO'         WHERE ETAPA = 'ETAPA_1_SUBMISSAO';
UPDATE RH_T_MISSAO_SERVICO SET ETAPA = 'ANALISE'           WHERE ETAPA = 'ETAPA_2_ANALISE_RH';
UPDATE RH_T_MISSAO_SERVICO SET ETAPA = 'EMISSAO_REQUISICAO' WHERE ETAPA = 'ETAPA_3_EMISSAO_REQUISICAO';
UPDATE RH_T_MISSAO_SERVICO SET ETAPA = 'LOGISTICA'         WHERE ETAPA = 'ETAPA_4_PROCESSAMENTO_LOGISTICO';
UPDATE RH_T_MISSAO_SERVICO SET ETAPA = 'CABIMENTO'         WHERE ETAPA = 'ETAPA_5_CABIMENTACAO_SGAL';
UPDATE RH_T_MISSAO_SERVICO SET ETAPA = 'CABIMENTO'         WHERE ETAPA = 'ETAPA_6_AUTORIZACAO_RH';
UPDATE RH_T_MISSAO_SERVICO SET ETAPA = 'PAGAMENTO'         WHERE ETAPA = 'ETAPA_7_PAGAMENTO_FINANCEIRO';

COMMIT;

-- Verificação: deve retornar 0 linhas com valores antigos
SELECT ETAPA, COUNT(*) AS TOTAL
FROM RH_T_MISSAO_SERVICO
GROUP BY ETAPA
ORDER BY ETAPA;
